"use client"

import { MonthSimulation, SimulationResult } from "@/types";
import { Line, LineChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatINR } from "@/lib/utils";

interface ScenarioComparisonChartProps {
    result: SimulationResult;
    startAge?: number;
}

export function ScenarioComparisonChart({ result, startAge }: ScenarioComparisonChartProps) {
    if (!result || !result.historyWorst || !result.historyBest) return null;

    // We assume all histories have the same length and month cadence if generated by the same runSimulation
    // We'll map based on the Median (result.history)

    // Downsample for performance (yearly data points)
    const data = result.history.filter((_, index) => index % 12 === 0).map((h, i) => {
        const year = Math.floor(h.month / 12);

        // Safely access other histories at the same index
        // Note: filtering creates a new array, so index 'i' here matches the filtered index
        // But the original histories are full length. 
        // We need to access the Correct Month index.
        const originalIndex = i * 12;

        const getDataAt = (hist: MonthSimulation[] | undefined) => {
            if (!hist || originalIndex >= hist.length) return 0;
            return Math.round(hist[originalIndex].totalFunds);
        };

        return {
            year,
            age: startAge ? startAge + year : undefined,
            name: startAge ? `Age ${startAge + year}` : `Year ${year}`,
            Median: Math.round(h.totalFunds),
            Worst: getDataAt(result.historyWorst),
            P25: getDataAt(result.historyP25),
            P75: getDataAt(result.historyP75),
            Best: getDataAt(result.historyBest),
        };
    });

    return (
        <Card className="glass-card w-full h-[500px]">
            <CardHeader>
                <CardTitle>Scenario Comparison Analysis</CardTitle>
                <CardDescription>
                    Compare portfolio performance across different market conditions.
                    Shows the range of possible outcomes from Worst Case (10th percentile) to Best Case (90th percentile).
                </CardDescription>
            </CardHeader>
            <CardContent className="h-[400px]">
                <ResponsiveContainer width="100%" height="100%">
                    <LineChart
                        data={data}
                        margin={{
                            top: 10,
                            right: 30,
                            left: 0,
                            bottom: 0,
                        }}
                    >
                        <CartesianGrid strokeDasharray="3 3" opacity={0.1} />
                        <XAxis
                            dataKey={startAge ? "age" : "year"}
                            tickFormatter={(v) => startAge ? `Age ${v}` : `Yr ${v}`}
                            stroke="#888888"
                            fontSize={12}
                            tickLine={false}
                            axisLine={false}
                        />
                        <YAxis
                            stroke="#888888"
                            fontSize={12}
                            tickLine={false}
                            axisLine={false}
                            tickFormatter={(val) => formatINR(val)}
                        />
                        <Tooltip
                            contentStyle={{ backgroundColor: 'rgba(255, 255, 255, 0.9)', borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                            itemStyle={{ fontSize: '12px' }}
                            labelStyle={{ color: '#666', fontWeight: 600, marginBottom: '4px' }}
                            formatter={(value: any) => [formatINR(Number(value)), ""]}
                            labelFormatter={(label) => startAge ? `Age ${label}` : `Year ${label}`}
                        />
                        <Legend verticalAlign="top" height={36} />

                        <Line type="monotone" name="Best (90th)" dataKey="Best" stroke="#10b981" strokeWidth={2} dot={false} strokeOpacity={0.6} />
                        <Line type="monotone" name="75th Percentile" dataKey="P75" stroke="#34d399" strokeWidth={2} dot={false} strokeDasharray="4 4" />

                        <Line type="monotone" name="Median (Typical)" dataKey="Median" stroke="#3b82f6" strokeWidth={3} dot={false} />

                        <Line type="monotone" name="25th Percentile" dataKey="P25" stroke="#f59e0b" strokeWidth={2} dot={false} strokeDasharray="4 4" />
                        <Line type="monotone" name="Worst (10th)" dataKey="Worst" stroke="#ef4444" strokeWidth={2} dot={false} strokeOpacity={0.8} />
                    </LineChart>
                </ResponsiveContainer>
            </CardContent>
        </Card>
    );
}
